window.SORIN = {
  business: {
    name: 'Sorin E BeautySpa', motto: 'We Pamper You',
    loyaltyOffer: 'Patronage Reward — Up to 15% Off',
    whatsapp: '2349046900500', phoneDisplay: '+234 904 690 0500',
    instagram: '@sorin_e_beautyspa', instagramUrl: 'https://www.instagram.com/sorin_e_beautyspa/',
    address: '1 Ado Ekiti Close, Off Emeka Anyaoku Street, Adjacent Alliance Hospital, Area 11, Garki, Abuja, Nigeria.',
    directions: 'https://www.google.com/maps/search/?api=1&query=1+Ado+Ekiti+Close,+Off+Emeka+Anyaoku+Street,+Area+11,+Garki,+Abuja,+Nigeria',
    hours: { primary: 'Monday–Saturday: Open 24 Hours', secondary: 'Sunday: Closed' }
  },
  services: [
    { category: 'Hair', items: [
      ['Washing & Blow Drying', 'Professional wash and blow-dry finish', '—', '5000'], ['Washing & Blow Drying with Argan Kits', 'Nourishing wash and blow-dry with argan kits', '—', '10000'], ['Natural Braids', 'Natural-hair braiding service', '—', '5000'], ['Natural Twist', 'Natural-hair twist styling', '—', '8000'], ['Steaming with Customer’s Kits', 'Hair steaming using your own kits', '—', '7000'], ['Steaming with Salon Kits', 'Hair steaming using salon kits', '—', '10000'], ['Traditional Organic Steaming', 'Traditional organic hair steaming treatment', '—', '12000'], ['Oil Hair Treatment', 'Restorative oil treatment', '—', '3000'], ['Anti-Dandruff Treatment', 'Targeted anti-dandruff treatment', '—', '5000'], ['Undo of Braids', 'Careful braid undo service', '—', '1000–3000'], ['Retouching with Customer’s Relaxer', 'Retouching using your own relaxer', '—', '7000'], ['Retouching with Salon Kits', 'Retouching using salon kits', '—', '10000'], ['Hair Colouring', 'Professional hair colouring', '—', '10000'], ['Different Styles', 'Price varies depending on the hairstyle. Contact us on WhatsApp for a personalized quote.', '—', 'Price varies'], ['Knotless Braids — Short & Less', 'Knotless braid styling', '—', '15000'], ['Knotless Braids — Short & Full', 'Knotless braid styling', '—', '20000'], ['Knotless Braids — Long & Less', 'Knotless braid styling', '—', '25000'], ['Knotless Braids — Long & Full', 'Knotless braid styling', '—', '30000'] ] },
    { category: 'Facials', items: [
      ['Deep Cleansing Facial', 'Deep-cleansing facial treatment', '—', '15000'], ['Gold Facial', 'Gold facial treatment', '—', '18000'], ['Acne Extraction & Exfoliation Facial', 'Targeted extraction and exfoliation treatment', '—', '18000'], ['Microdermabrasion', 'Professional microdermabrasion treatment', '—', '20000'], ['Vitamin C Facial', 'Vitamin C facial treatment', '—', '18000'], ['Whitening Facial', 'Brightening facial treatment', '—', '20000'], ['Dermaplaning Facial', 'Professional dermaplaning facial', '—', '18000'], ['Hyperpigmentation & Sunburn Treatment', 'Targeted facial care treatment', '—', '20000'] ] },
    { category: 'Hammam & Body Treatments', items: [
      ['Brightening Souq Hammam', 'Exfoliation and brightening treatment with deep cleansing and four different herbs for glowing, refreshed skin.', '—', '40000'], ['Sorin E Special Hammam', 'Full-body exfoliation with a natural brightening mask for an even, glowing complexion.', '—', '35000'], ['Queen Sheba Hammam', 'Vitamin C brightening scrub, glowing polish, body wrap and waxing; waxing may be replaced with massage or Swedish massage where applicable.', '1 hr 50 min', '40000'], ['Moroccan Hammam Bath — Royal/Gold Package', 'Suglah Hammam, Dika exfoliating scrub, waxing or facial/massage option, turmeric milk polish/Kurkum, four scrubs and vaginal steam.', '2 hrs 30 min', '40000'], ['Silver Package', 'Turmeric milk polish/Kurkum, different scrubs, vaginal steam and body waxing.', '1 hr 30 min', '35000'], ['Traditional Hammam', 'Exfoliation and mask, deep cleansing and seven different herbs for glowing skin.', '40 min', '37000'], ['Coffee Scrub / Chocolate Scrub', 'Body exfoliation for dry-feeling skin, leaving it smoother and refreshed.', '—', '36000'] ] },
    { category: 'Waxing', items: [
      ['Brazilian Waxing', 'Professional Brazilian waxing', '—', '4000'], ['Underarms', 'Underarm waxing', '—', '2500'], ['Back Waist', 'Back waist waxing', '—', '3000'], ['Chest/Stomach', 'Chest or stomach waxing', '—', '4000'], ['Chin Wax', 'Chin waxing', '—', '2500'], ['Knee/Feet', 'Knee or feet waxing', '—', '2500'], ['Thigh/Knee', 'Thigh or knee waxing', '—', '2500'], ['Arm', 'Arm waxing', '—', '2000'], ['Elbow/Fingers', 'Elbow or fingers waxing', '—', '2500'], ['Full Bikini Line', 'Full bikini line waxing', '—', '2500'], ['Full Body Wax — excluding Brazilian & Underarms', 'Full-body waxing that does not include Brazilian or underarm waxing.', '—', '8000'], ['Full Body Wax — including Brazilian & Underarms', 'Full-body waxing including Brazilian and underarm waxing.', '—', '12000'] ] },
    { category: 'Nails / Hands & Feet', items: [
      ['Manicure', 'Hand care and manicure service', '—', '3000'], ['Manicure + Gel Polish', 'Manicure with gel polish', '—', '5000'], ['Pedicure', 'Foot care and pedicure service', '—', '10000'], ['Pedicure + Gel Polish', 'Pedicure with gel polish', '—', '12000'], ['Jelly Pedicure', 'Jelly pedicure service', '—', '12000'], ['Organic Pedicure', 'Organic pedicure service', '—', '12000'] ] }
  ],
  packages: [
    ['Brightening Souq Hammam', 'Exfoliation, deep cleansing and four different herbs for glowing, refreshed skin.', '—', '40000'], ['Sorin E Special Hammam', 'Full-body exfoliation and natural brightening mask.', '—', '35000'], ['Queen Sheba Hammam', 'Vitamin C scrub, body polish and wrap, with waxing or massage replacement where applicable.', '1 hr 50 min', '40000'], ['Moroccan Hammam Bath — Royal/Gold Package', 'Suglah Hammam, Dika scrub, treatment choice, turmeric milk polish/Kurkum, four scrubs and vaginal steam.', '2 hrs 30 min', '40000'], ['Silver Package', 'Turmeric milk polish/Kurkum, scrubs, vaginal steam and body waxing.', '1 hr 30 min', '35000'], ['Traditional Hammam', 'Exfoliation, mask, deep cleansing and seven different herbs.', '40 min', '37000']
  ],
  memberships: [
    ['Patronage Reward', 'A thoughtful thank-you for your loyalty.', ['Up to 15% off based on customer patronage', 'The more you patronize Sorin E BeautySpa, the more you enjoy our appreciation for your loyalty.', 'Discount eligibility is confirmed directly with our team']]
  ],
  products: { enabled: false, note: 'Beauty products will be added with confirmed photos, names, prices and descriptions.' }
};
