(() => {
  const { business, services, packages, memberships, products } = window.SORIN;
  const money = value => /^\d+$/.test(String(value)) ? `₦${Number(value).toLocaleString('en-NG')}` : value;
  const safe = value => String(value || '').replace(/[<>]/g, '');
  const waUrl = message => `https://wa.me/${business.whatsapp}?text=${encodeURIComponent(message)}`;
  const wireLinks = (scope=document) => scope.querySelectorAll('.whatsapp-link').forEach(el => { el.href = waUrl(el.dataset.wa || 'Hello Sorin E BeautySpa, I would like to make an enquiry.'); el.target = '_blank'; el.rel = 'noopener'; });

  document.head.insertAdjacentHTML('beforeend', `<style>.logo img{width:145px;height:54px;object-fit:contain;mix-blend-mode:multiply}.logo{gap:10px}.logo>span:not(.logo-motto){display:none}.logo-motto{font:700 8px 'DM Sans',sans-serif!important;letter-spacing:.15em!important;line-height:1!important;white-space:nowrap}.offer{padding:88px 8vw;background:#e7d3b4;text-align:center}.offer h2{font:500 clamp(38px,4.3vw,62px)/1 'Playfair Display',serif;letter-spacing:-.05em;margin:0}.offer h2 em{font-style:italic}.offer p:not(.eyebrow){max-width:600px;margin:20px auto 27px}.media-placeholder{min-height:100%;width:100%;display:grid;place-items:center;text-align:center;padding:28px;background:linear-gradient(135deg,#1b423c,#b9995c);color:#fff;font:600 12px/1.6 'DM Sans';letter-spacing:.12em}.media-placeholder span{max-width:250px}.gallery-grid .media-placeholder{min-height:180px}.footer-logo img{background:#fff}@media(max-width:540px){.logo img{width:110px;height:42px}.logo-motto{display:none}}</style>`);
  const favicon = document.querySelector('link[rel="icon"]'); if (favicon) { favicon.href = 'sorin-e-logo.jpeg'; favicon.type = 'image/jpeg'; }
  document.querySelectorAll('.logo img').forEach(img => { img.src = 'sorin-e-logo.jpeg'; img.alt = 'Sorin E Beauty Spa logo'; });
  document.querySelectorAll('.logo > span').forEach(span => { span.className = 'logo-motto'; span.textContent = business.motto; });
  const eyebrow = document.querySelector('.hero-copy .eyebrow'); if (eyebrow) eyebrow.textContent = `${business.motto.toUpperCase()} · ABUJA'S BEAUTY & WELLNESS SANCTUARY`;
  const offer = document.createElement('section'); offer.className = 'offer'; offer.innerHTML = `<p class="eyebrow">PATRONAGE REWARD</p><h2>Up to <em>15% off</em></h2><p>The more you patronize Sorin E BeautySpa, the more you enjoy our appreciation for your loyalty. Your available discount is confirmed directly with our team.</p><a class="button dark whatsapp-link" data-wa="Hello Sorin E BeautySpa, I would like to ask about the patronage reward.">Ask about your reward →</a>`; document.querySelector('.promise').before(offer);
  document.querySelector('.membership .eyebrow').textContent = 'PATRONAGE REWARD';
  document.querySelector('.hours-card em').textContent = business.hours.secondary.toUpperCase();
  document.querySelectorAll('footer p').forEach(el => { if (/SUNDAY/i.test(el.textContent)) el.textContent = business.hours.secondary.toUpperCase(); });
  document.querySelector('.membership .section-title h2').innerHTML = 'Loyalty, <em>appreciated.</em>';
  document.querySelector('.membership .section-title p:not(.eyebrow)').textContent = 'The more you patronize Sorin E BeautySpa, the more you enjoy our appreciation for your loyalty. Ask our team about the reward available for your appointment.';
  const useImage = (selector, source, alt) => document.querySelectorAll(selector).forEach(node => { node.src = source; node.alt = alt; node.removeAttribute('srcset'); });
  useImage('.hero-image img', 'media/photos/p1.jpeg', 'Hot stone therapy at Sorin E BeautySpa');
  useImage('.photo-frame img', 'media/photos/p2.jpeg', 'Foot spa treatment at Sorin E BeautySpa');
  document.querySelector('.gallery .section-title p:not(.eyebrow)').textContent = 'A glimpse inside the Sorin E BeautySpa experience.';
  document.querySelectorAll('[data-address]').forEach(el => el.textContent = business.address);
  document.querySelectorAll('[data-phone]').forEach(el => { el.textContent = business.phoneDisplay; el.href = `tel:+${business.whatsapp}`; });
  document.querySelectorAll('[data-directions]').forEach(el => { el.href = business.directions; el.target = '_blank'; el.rel = 'noopener'; });
  document.querySelectorAll('[data-instagram]').forEach(el => { el.textContent = `Follow ${business.instagram} ↗`; el.href = business.instagramUrl; el.target = '_blank'; el.rel = 'noopener'; });
  document.getElementById('year').textContent = new Date().getFullYear();
  document.getElementById('serviceCategories').innerHTML = services.map((group, i) => `<article class="category-card"><h3>${group.category}</h3><p>${group.items.length} confirmed services. Contact us for treatment details.</p><a href="#pricing" data-category="${i}">Explore treatments →</a></article>`).join('');
  document.querySelector('.services .disclaimer').textContent = 'All listed prices are confirmed. Where a service says “Price varies”, contact us on WhatsApp for a personalised quote.';
  document.getElementById('packages').innerHTML = packages.map(([name, detail, duration, price]) => `<article class="package"><div><h3>${name}</h3><p>${detail}</p></div><b>${money(price)}</b><small>${duration !== '—' ? duration : ''}</small><a class="whatsapp-link" data-wa="Hello Sorin E BeautySpa, I'm interested in the ${name}. Please share more details.">Book on WhatsApp →</a></article>`).join('');
  document.getElementById('memberships').innerHTML = memberships.map(([name, intro, benefits]) => `<article class="member"><h3>${name}</h3><p>${intro}</p><ul>${benefits.map(x => `<li>${x}</li>`).join('')}</ul><a class="whatsapp-link" data-wa="Hello Sorin E BeautySpa, I would like to ask about the patronage reward.">Ask about your reward →</a></article>`).join('');
  const productSection = document.createElement('section'); productSection.className = 'offer'; productSection.id = 'products'; productSection.innerHTML = `<p class="eyebrow">BEAUTY PRODUCTS</p><h2>Your ritual, <em>continued.</em></h2><p>Our beauty product area is ready for the confirmed Sorin E range. For current product availability and personalised recommendations, please speak directly with our team.</p><a class="button dark whatsapp-link" data-wa="Hello Sorin E BeautySpa, I would like to ask about your current beauty products.">Ask about products →</a>`; document.querySelector('.gallery').before(productSection);
  const tabs = document.getElementById('priceTabs'), list = document.getElementById('priceList');
  function renderPrices(index=0) { const group = services[index]; tabs.querySelectorAll('button').forEach((button, n) => button.classList.toggle('active', n === index)); list.innerHTML = group.items.map(([name, desc, duration, price]) => `<article class="price-row"><h3>${name}</h3><p>${desc}</p><span>${duration}</span><b>${money(price)}</b><a class="whatsapp-link" data-wa="Hello Sorin E BeautySpa, I would like to book ${name}${/^\d+$/.test(price) ? ` (${money(price)})` : ''}.">Book now →</a></article>`).join(''); wireLinks(list); }
  tabs.innerHTML = services.map((group, i) => `<button class="${i===0?'active':''}" type="button">${group.category}</button>`).join(''); tabs.querySelectorAll('button').forEach((button, index) => button.addEventListener('click', () => renderPrices(index))); renderPrices();
  const select = document.getElementById('bookingService'); select.innerHTML = `<option value="">Choose a treatment</option>${services.flatMap(group => group.items.map(item => `<option value="${item[0]}">${group.category} — ${item[0]}${/^\d+$/.test(item[3]) ? ` (${money(item[3])})` : ''}</option>`)).join('')}`;
  const form = document.getElementById('bookingForm'), message = form.querySelector('.form-message'); form.addEventListener('submit', event => { event.preventDefault(); if (!form.checkValidity()) { message.textContent = 'Please complete all required fields before continuing.'; form.reportValidity(); return; } const data = Object.fromEntries(new FormData(form)); const text = `Hello Sorin E BeautySpa,\n\nI would like to book an appointment.\n\nName: ${safe(data.name)}\nPhone: ${safe(data.phone)}\nEmail: ${safe(data.email)}\nService: ${safe(data.service)}\nPreferred Date: ${safe(data.date)}\nPreferred Time: ${safe(data.time)}\nNumber of Guests: ${safe(data.guests)}\n\nAdditional Request:\n${safe(data.notes) || 'None'}\n\nPlease confirm availability and appointment details.\n\nThank you.`; message.textContent = 'Your booking request is ready. Opening WhatsApp to confirm availability…'; window.open(waUrl(text), '_blank', 'noopener'); });
  wireLinks(); document.querySelectorAll('[data-category]').forEach(el => el.addEventListener('click', () => renderPrices(Number(el.dataset.category))));
  const header = document.querySelector('header'), menu = document.querySelector('.menu'); menu.addEventListener('click', () => { const open = header.classList.toggle('open'); menu.setAttribute('aria-expanded', open); }); document.querySelectorAll('nav a').forEach(link => link.addEventListener('click', () => header.classList.remove('open')));
})();
